package paa_test

import (
	"image"
	"image/png"
	"io"
	"os"
	"testing"

	"github.com/jmhobbs/go-paa"
	"github.com/raf555/pixelmatch"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const PIXELMATCH_THRESHOLD = 0.05 // half the default of 0.1

func Test_Decode_DX1_TestFile(t *testing.T) {
	// This is a test file generated by ImageToPAA
	f, err := os.Open("testdata/test-pattern.paa")
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		if err := f.Close(); err != nil {
			t.Logf("failed to close test file: %v", err)
		}
	}()

	img, err := paa.Decode(f)
	require.NoError(t, err)
	require.NotNil(t, img)

	require.NotNil(t, img.AVGC, "AVGC should not be nil")
	assert.Equal(t, uint8(0xb6), img.AVGC.Red)
	assert.Equal(t, uint8(0xaa), img.AVGC.Green)
	assert.Equal(t, uint8(0xa9), img.AVGC.Blue)
	assert.Equal(t, uint8(0xff), img.AVGC.Alpha)

	require.NotNil(t, img.MAXC, "MAXC should not be nil")
	assert.Equal(t, [4]uint8{0xff, 0xff, 0xff, 0xff}, img.MAXC.Data)

	require.NotNil(t, img.OFFS, "OFFS should not be nil")
	assert.Equal(
		t,
		[16]uint32{
			0x70,
			0x02f6,
			0x0472,
			0x1479,
			0x1880,
			0x1987,
			0x19ce,
			// everything else is 0x00
		},
		img.OFFS.Offsets,
	)

	require.Equal(t, 8, len(img.Mipmaps))
	assert.True(t, img.Mipmaps[0].Compressed)
	assert.Equal(t, 512, int(img.Mipmaps[0].Width))
	assert.Equal(t, 256, int(img.Mipmaps[0].Height))

	assert.True(t, img.Mipmaps[1].Compressed)
	assert.Equal(t, 256, int(img.Mipmaps[1].Width))
	assert.Equal(t, 128, int(img.Mipmaps[1].Height))

	assert.False(t, img.Mipmaps[2].Compressed)
	assert.Equal(t, 128, int(img.Mipmaps[2].Width))
	assert.Equal(t, 64, int(img.Mipmaps[2].Height))

	assert.False(t, img.Mipmaps[3].Compressed)
	assert.Equal(t, 64, int(img.Mipmaps[3].Width))
	assert.Equal(t, 32, int(img.Mipmaps[3].Height))

	assert.False(t, img.Mipmaps[4].Compressed)
	assert.Equal(t, 32, int(img.Mipmaps[4].Width))
	assert.Equal(t, 16, int(img.Mipmaps[4].Height))

	assert.False(t, img.Mipmaps[5].Compressed)
	assert.Equal(t, 16, int(img.Mipmaps[5].Width))
	assert.Equal(t, 8, int(img.Mipmaps[5].Height))

	assert.False(t, img.Mipmaps[6].Compressed)
	assert.Equal(t, 8, int(img.Mipmaps[6].Width))
	assert.Equal(t, 4, int(img.Mipmaps[6].Height))

	// Why is this one 0x0?
	assert.False(t, img.Mipmaps[7].Compressed)
	assert.Equal(t, 0, int(img.Mipmaps[7].Width))
	assert.Equal(t, 0, int(img.Mipmaps[7].Height))

	t.Logf("size: %d, offset: %d", img.Mipmaps[0].Size, img.Mipmaps[0].Offset)

	r, err := img.Mipmaps[0].Reader(f)
	require.NoError(t, err)
	bytes, err := io.ReadAll(r)
	require.NoError(t, err)
	assert.Equal(t, 65536, len(bytes)) // 512x256/2 (DXT1 - 1 nibble per pixel)

	rgba, err := img.Mipmaps[0].Image(f)
	require.NoError(t, err)
	assert.Equal(t, image.Rectangle{Max: image.Pt(512, 256)}, rgba.Bounds())
	assert.Equal(t, 512*4, rgba.Stride)

	pngF, err := os.Open("testdata/test-pattern.png")
	require.NoError(t, err)

	expected, err := png.Decode(pngF)
	require.NoError(t, err)

	diff, err := pixelmatch.Compare(expected, rgba, pixelmatch.WithThreshold(PIXELMATCH_THRESHOLD))
	require.NoError(t, err)
	assert.Zero(t, diff)
}
