package paa_test

import (
	"os"
	"testing"

	"github.com/jmhobbs/go-paa"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_Decode_DX1_TestFile(t *testing.T) {
	// This is a test file generated by ImageToPAA
	f, err := os.Open("testdata/test-pattern.paa")
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		if err := f.Close(); err != nil {
			t.Logf("failed to close test file: %v", err)
		}
	}()

	img, err := paa.Decode(f)
	require.NoError(t, err)
	require.NotNil(t, img)

	require.NotNil(t, img.AVGC, "AVGC should not be nil")
	assert.Equal(t, uint8(0xb6), img.AVGC.Red)
	assert.Equal(t, uint8(0xaa), img.AVGC.Green)
	assert.Equal(t, uint8(0xa9), img.AVGC.Blue)
	assert.Equal(t, uint8(0xff), img.AVGC.Alpha)

	require.NotNil(t, img.MAXC, "MAXC should not be nil")
	assert.Equal(t, [4]uint8{0xff, 0xff, 0xff, 0xff}, img.MAXC.Data)

	require.NotNil(t, img.OFFS, "OFFS should not be nil")
	assert.Equal(
		t,
		[16]uint32{
			0x70,
			0x02f6,
			0x0472,
			0x1479,
			0x1880,
			0x1987,
			0x19ce,
			// everything else is 0x00
		},
		img.OFFS.Offsets,
	)

	require.Equal(t, 1, len(img.Mipmaps))
	assert.True(t, img.Mipmaps[0].Compressed)
	assert.Equal(t, 512, int(img.Mipmaps[0].Width))
	assert.Equal(t, 256, int(img.Mipmaps[0].Height))
}
